<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  

  <title>C&#43;&#43;: Exceptions and destroyers - Julio Merino</title>
  <meta content="C&#43;&#43;: Exceptions and destroyers - Julio Merino" property="og:title">

  
  <meta name="description" content="If you use exceptions to signal errors in C&#43;&#43;, you should be really careful when throwing an exception from inside a class&#39; destroyer function, because you can easily cause an abort trap. Consider the following code:
struct test {
~test(void) {
throw int(0);
}
};
int main(void) {
try {
test t;
throw int(1);
} catch (int e) {
} catch (...) {
}
return 0;
}
Trivial, isn&#39;t it? Well, now compile it and run it: you will get a &#34;">
  <meta name="author" content="Julio Merino">
  <meta name="generator" content="Hugo 0.36.1" />

  <meta content="http://julio.meroh.net/2005/02/c-exceptions-and-destroyers.html" property="og:url">

  <link rel="canonical" href="http://julio.meroh.net/2005/02/c-exceptions-and-destroyers.html">
  <link rel="alternate" type="application/rss+xml"
        title="Julio Merino" href="/feed.xml" />

  <link rel="stylesheet" href="/css/main.css">
  <link rel="stylesheet" href="/css/chroma.css">

  
  <!--[if lt IE 9]>
    <script src="/js/html5shiv-3.7.2.min.js"></script>
    <script src="/js/respond-1.4.2.min.js"></script>
  <![endif]-->
</head>


  <body>
    <header class="site-header">

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Julio Merino</a>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
          
            <li><a class="page-link" href="/about.html" >About</a></li>
          
        
          
            <li><a class="page-link" href="/essays.html" >Essays</a></li>
          
        
          
            <li><a class="page-link" href="/software.html" >Software</a></li>
          
        
          
            <li><a class="page-link" href="/work.html" >Work</a></li>
          
        
      </ul>

      <form class="navbar-form navbar-right" method="get" role="search"
            action="http://www.google.com/search">
          <div class="form-group">
            <input type="text" name="query" class="form-control"
                   placeholder="Search">
            <input type="hidden" name="sitesearch" value="http://julio.meroh.net/">
          </div>
          <button type="submit" value="Search" class="btn btn-default">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          </button>
      </form>
    </div>
  </div>
</nav>

</header>


    <div class="page-header">
      <div class="container">
        <h1>C&#43;&#43;: Exceptions and destroyers</h1>

        <p>February 7, 2005</p>

        
      </div>
    </div>

    <div class="container">
      <article>
        <p>If you use exceptions to signal errors in C++, you should be really careful when throwing an exception from inside a class' destroyer function, because you can easily cause an abort trap. Consider the following code:</p>  <pre>struct test {<br />  ~test(void) {<br />      throw int(0);<br />  }<br />};<br /><br />int main(void) {<br />  try {<br />      test t;<br />      throw int(1);<br />  } catch (int e) {<br />  } catch (...) {<br />  }<br /><br />  return 0;<br />}</pre><p></p>  <p>Trivial, isn't it?  Well, now compile it and run it: you will get a "nice" core dump.  However, if you disable the <tt>throw</tt> statement inside <tt>~test</tt>, the problem will go away.  The problem will also disappear if you move <tt>test</tt>'s instantiation outside the try block.</p>  <p>But... why does this happen?  When the <tt>int(1)</tt> exception is thrown, the <tt>t</tt> object has to be destroyed before it can be handled, because its scope has to be cleaned (see how it's placed inside the try block). When this happens, the destroyer function throws a new exception (while we were handling another one), which could produce an infinite loop. Voila, you've got the abort trap.</p>  <p>So be aware when throwing an exception from a destroyer. Simply put, you must make sure that they will not generate exceptions; you have to handle any possible failure from within them.</p><p class="mobile-post"></p>

      </article>

      <div class="post-links">
        <p>
          

          

          <a href="/feed.xml">Subscribe via RSS</a>
          &middot;
          <a href="/blog">Go to posts index</a>
        </p>

        <form class="form-inline"
            action="https://feedburner.google.com/fb/a/mailverify"
            method="post"
            target="popupwindow"
            onsubmit="window.open('https://feedburner.google.com/fb/a/mailverify?uri=jmmv', 'popupwindow', 'scrollbars=yes,width=550,height=520');return true">
          <div class="form-group form-group-sm">
            <input type="text" style="width: 400px" name="email"
                    placeholder="Enter your email to subscribe to new posts"
                    class="form-control input-sm"/>
          </div>
          <button type="submit" value="Subscribe"
                  class="btn btn-default btn-sm">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
          </button>
          &nbsp;&nbsp;&nbsp;Delivered by
          <input type="hidden" value="jmmv" name="uri"/>
          <input type="hidden" name="loc" value="en_US"/>
          <a href="https://feedburner.google.com" target="_blank">FeedBurner</a>
        </form>
      </div>

      <div id="disqus_thread">
        <script>
          var disqus_config = function () {
            this.page.url = "http:\/\/julio.meroh.net\/2005\/02\/c-exceptions-and-destroyers.html";
            this.page.identifier = "2005-02-07-c-exceptions-and-destroyers";
          };
          (function() { 
            var d = document, s = d.createElement('script');

            s.src = '//jmmv.disqus.com/embed.js';

            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
          })();
        </script>
        <noscript>Please enable JavaScript to view the
          <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments
          powered by Disqus.</a>
        </noscript>
      </div>
      
      <p>Comments from the original Blogger-hosted post:</p>
      <script src="https://apis.google.com/js/plusone.js"></script>
      <div class="g-comments"
           data-href="http://julipedia.meroh.net/2005/02/c-exceptions-and-destroyers.html"
           data-first_party_property="BLOGGER"
           data-view_type="FILTERED_POSTMOD">
      </div>
      
    </div>

    <div class="container">
  <footer>
    <p class="pull-right"><a href="#">Back to top</a></p>
    <p>Copyright 2018 Julio Merino</p>
  </footer>
</div>

<script src="/js/jquery-1.11.2.min.js"></script>
<script src="/css/bootstrap.min.js"></script>

<script>
$("p:contains('NOTE: ')").addClass("callout callout-info");
$("p:contains('IMPORTANT: ')").addClass("callout callout-info");
$("p:contains('WARNING: ')").addClass("callout callout-warning");
$("p:contains('DANGER: ')").addClass("callout callout-danger");
</script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;
  m.parentNode.insertBefore(a,m)})(window,document,'script',
  '//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-63557333-1', 'auto');
  ga('send', 'pageview');
</script>

  </body>
</html>
